# Pull the base image.
FROM alpine:latest

# Run everything as one command so that only one layer is created
RUN apk --update add --no-cache --virtual build-dependencies wget \
    && apk --update add --no-cache nmap nmap-scripts bc tcptraceroute iputils \
    && wget https://raw.githubusercontent.com/vulnersCom/nmap-vulners/master/vulners.nse -O /usr/share/nmap/scripts/vulners.nse \
    && nmap --script-updatedb \
    && wget http://www.vdberg.org/~richard/tcpping -O /usr/local/bin/tcping \
    && chmod +x /usr/local/bin/tcping \
    && apk del --purge build-dependencies \
    && rm -rf /var/cache/apk/* \
    && rm -rf /root/.cache
