#!/bin/bash
## Non functional or unprocessed word will goes here..!! 

alias kirana=" "
alias tolong=" "
alias coba=" "
alias berapa=" "
alias sekarang=" "
alias kamu=" "
alias saya=" "
alias gue=" "
alias emang=" "
alias kita=" "
alias mau=" "
alias saatnya=" "
