#!/bin/bash
# This is for error or command not found response
# if the command-not-found package is installed, use it

if [ -x /usr/lib/command-not-found -o -x /usr/share/command-not-found/command-not-found ]; then
        function command_not_found_handle {
                # check because c-n-f could've been removed in the meantime
                if [ -x /usr/lib/command-not-found ]; then
                   /bin/echo " "
                   /bin/echo "${red}Kirana.Systems => Hmm... Maksudnya mas $USER apa ya? ${white}"
                   /bin/echo " "
                elif [ -x /usr/share/command-not-found/command-not-found ]; then
                   /bin/echo " "
                   /bin/echo "${red}Kirana.Systems => Hmm... Maksudnya mas $USER apa ya? ${white}"
                   /bin/echo " "
                else
                   /bin/echo " "
                   /bin/echo "${red}Kirana.Systems => Hmm... Maksudnya mas $USER apa ya? ${white}"
                   /bin/echo " "
                fi
        }
fi
