#!/bin/bash
#
## Upgrade her 

## Kirana's environment
kiranahome="/home/$USER/.kirana"

## Return PATH to default in order to avoid the chaos!!
export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

## Let's paint the world!!
red=`/usr/bin/tput setaf 1`
white=`/usr/bin/tput setaf 7`
magenta=`/usr/bin/tput setaf 5`

gitpull="/usr/bin/git pull" 

## Greetings
echo "${red}"
echo "Kirana.Systems => Untuk cek pelajaran baru buat Kirana." 
echo "Kirana.Systems => Mas $USER bilang aja, kirana saatnya belajar" 
echo "Kirana.Systems => Sebentar ya mas $USER. Kirana cek ada pelajaran baru apa nggak" 
echo "${magenta}"

## Kirana don't need root to run this file. Yet.
if [ $(id -u) = "0" ]; then
    echo "${red}"
    echo "Kirana.Systems => Maaf mas $USER. Kirana jangan dijalankan sebagai root ya" 
    echo "${white}"
    exit 1
fi

## Update her just by cloning from github 
cd $kiranahome
$gitpull

## Return PATH to Kirana's setting 
export PATH=${HOME}/.kirana

## Done
echo "${red}"
echo "Kirana.Systems => Terima kasih mas $USER" 
echo "${white}"
